/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 김두현
 */
public class HashTag extends javax.swing.JFrame {

    public HashTag() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        해시검색_jScrollPane = new javax.swing.JScrollPane();
        Hash메뉴_jTable = new javax.swing.JTable();
        장바구니_jButton = new javax.swing.JButton();
        메뉴_jLabel = new javax.swing.JLabel();
        장바구니_jTabbedPane = new javax.swing.JTabbedPane();
        Hash장바구니_jScrollPane = new javax.swing.JScrollPane();
        Hash장바구니_jTable = new javax.swing.JTable();
        사이즈_jComboBox = new javax.swing.JComboBox<>();
        총합계_jLabel = new javax.swing.JLabel();
        결제_jButton = new javax.swing.JButton();
        Hash해시값_jLabel = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Hash메뉴_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MENU", "SIZE", "PRICE"
            }
        ));
        Hash메뉴_jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Hash메뉴_jTableMouseClicked(evt);
            }
        });
        해시검색_jScrollPane.setViewportView(Hash메뉴_jTable);

        장바구니_jButton.setText("장바구니 담기");
        장바구니_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                장바구니_jButtonActionPerformed(evt);
            }
        });

        메뉴_jLabel.setText("MENU");

        Hash장바구니_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MENU", "SIZE", "PRICE"
            }
        ));
        Hash장바구니_jScrollPane.setViewportView(Hash장바구니_jTable);

        장바구니_jTabbedPane.addTab("장바구니", Hash장바구니_jScrollPane);

        사이즈_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Small", "Medium", "Large" }));
        사이즈_jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                사이즈_jComboBoxActionPerformed(evt);
            }
        });

        결제_jButton.setText("결제하기");
        결제_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                결제_jButtonActionPerformed(evt);
            }
        });

        jButton4.setText("뒤로가기");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(장바구니_jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                    .addComponent(해시검색_jScrollPane))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(장바구니_jButton)
                    .addComponent(메뉴_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(사이즈_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(결제_jButton)
                    .addComponent(총합계_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4)
                .addGap(196, 196, 196)
                .addComponent(Hash해시값_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Hash해시값_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(해시검색_jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(메뉴_jLabel)
                        .addGap(18, 18, 18)
                        .addComponent(사이즈_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(장바구니_jButton)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(장바구니_jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(총합계_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(결제_jButton)))
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        HashSearch hashsearch = new HashSearch();
        String k = hashsearch.getHashSearch();
        Hash해시값_jLabel.setText(k);
        DefaultTableModel model = (DefaultTableModel) Hash메뉴_jTable.getModel();
        Connection con = null;
        PreparedStatement st = null;
        ResultSet rs = null;

        String sql = "select * from menu_info join store_info using (store_number) where menu_info.menu_hashtag = ";

        try {
            con = DriverManager.getConnection("jdbc:mysql://115.85.182.30:3306/cse_swde_DB?zeroDateTimeBehavior=CONVERT_TO_NULL&characterEncoding=UTF-8&serverTimezone=UTC", "cse_swde", "password");
            st = con.prepareStatement(sql + "'" + k + "'");
            JOptionPane.showMessageDialog(null, "연결성공");

            rs = st.executeQuery();
            while (rs.next()) {
                String menu = rs.getString("menu_name");
                String size = rs.getString("menu_size");
                String price = rs.getString("menu_price");

                Object data[] = {menu, size, price};
                model.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(StoreList.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_formWindowOpened

    private void Hash메뉴_jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Hash메뉴_jTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) Hash메뉴_jTable.getModel();
        int i = Hash메뉴_jTable.getSelectedRow();

        메뉴_jLabel.setText(model.getValueAt(i, 0).toString());
    }//GEN-LAST:event_Hash메뉴_jTableMouseClicked

    private void 장바구니_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_장바구니_jButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) Hash장바구니_jTable.getModel();

        Object[] row = new Object[3];
        row[0] = 메뉴_jLabel.getText();
        row[1] = 사이즈_jComboBox.getSelectedItem();
        String price;
        if (row[0].equals("")) {
            JOptionPane.showMessageDialog(null, "메뉴를 선택해 주세요.");
        } else if (row[0].equals("Americano")) {
            if (row[1].equals("-")) {
                JOptionPane.showMessageDialog(null, "사이즈를 선택해 주세요.");
            } else if (row[1].equals("Small")) {
                price = "4100";
                row[2] = price;
                model.addRow(row);
                메뉴_jLabel.setText("");
                사이즈_jComboBox.setSelectedItem("-");
            } else if (row[1].equals("Medium")) {
                price = "4600";
                row[2] = price;
                model.addRow(row);
                메뉴_jLabel.setText("");
                사이즈_jComboBox.setSelectedItem("-");
            } else if (row[1].equals("Large")) {
                price = "5100";
                row[2] = price;
                model.addRow(row);
                메뉴_jLabel.setText("");
                사이즈_jComboBox.setSelectedItem("-");
            }
        }
        int sum = 0;

        for (int i = 0; i < Hash장바구니_jTable.getRowCount(); i++) {
            String pocket = Hash장바구니_jTable.getValueAt(i, 2).toString();
            int s = Integer.parseInt(pocket);
            sum += s;
            String money = Integer.toString(sum);
            총합계_jLabel.setText(money);
        }

    }//GEN-LAST:event_장바구니_jButtonActionPerformed

    private void 사이즈_jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_사이즈_jComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_사이즈_jComboBoxActionPerformed

    private void 결제_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_결제_jButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_결제_jButtonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        User user = new User();
        user.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HashTag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HashTag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HashTag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HashTag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HashTag().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Hash메뉴_jTable;
    private javax.swing.JScrollPane Hash장바구니_jScrollPane;
    private javax.swing.JTable Hash장바구니_jTable;
    private javax.swing.JLabel Hash해시값_jLabel;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton 결제_jButton;
    private javax.swing.JLabel 메뉴_jLabel;
    private javax.swing.JComboBox<String> 사이즈_jComboBox;
    private javax.swing.JButton 장바구니_jButton;
    private javax.swing.JTabbedPane 장바구니_jTabbedPane;
    private javax.swing.JLabel 총합계_jLabel;
    private javax.swing.JScrollPane 해시검색_jScrollPane;
    // End of variables declaration//GEN-END:variables
}
