/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import Decorator.Basic;
import Decorator.Menu;
import Memento.CareTaker;
import Memento.Information;
import Strategy.OptionPrice;
import Strategy.Price;
import static User.Store.Menu_jLabel;
import static User.Store.Size_jComboBox;
import static User.User.Hashsearch_jTextField;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 김두현
 */
public class HashtagStore extends javax.swing.JFrame {

    public HashtagStore() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu_jLabel = new javax.swing.JLabel();
        jTabbedPane = new javax.swing.JTabbedPane();
        Menu_Panel = new javax.swing.JPanel();
        Menu_jScrollPane = new javax.swing.JScrollPane();
        Menu_jTable = new javax.swing.JTable();
        Basket_jTabbedPane = new javax.swing.JTabbedPane();
        Basket_jScrollPane = new javax.swing.JScrollPane();
        Basket_jTable = new javax.swing.JTable();
        Basket_jButton = new javax.swing.JButton();
        Menu_jLabel1 = new javax.swing.JLabel();
        Size_jComboBox = new javax.swing.JComboBox<>();
        Storename_jLabel = new javax.swing.JLabel();
        Back_jButton = new javax.swing.JButton();

        Menu_jLabel.setText("-");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Menu_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MENU", "SIZE", "PRICE"
            }
        ));
        Menu_jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_jTableMouseClicked(evt);
            }
        });
        Menu_jScrollPane.setViewportView(Menu_jTable);

        Basket_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MENU", "SIZE", "PRICE"
            }
        ));
        Basket_jScrollPane.setViewportView(Basket_jTable);

        Basket_jTabbedPane.addTab("장바구니", Basket_jScrollPane);

        Basket_jButton.setText("장바구니 담기");
        Basket_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Basket_jButtonActionPerformed(evt);
            }
        });

        Menu_jLabel1.setText("-");

        Size_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Small", "Medium", "Large" }));
        Size_jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Size_jComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Menu_PanelLayout = new javax.swing.GroupLayout(Menu_Panel);
        Menu_Panel.setLayout(Menu_PanelLayout);
        Menu_PanelLayout.setHorizontalGroup(
            Menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Basket_jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                    .addGroup(Menu_PanelLayout.createSequentialGroup()
                        .addComponent(Menu_jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Basket_jButton)))
                .addGap(18, 18, 18)
                .addGroup(Menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Menu_jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Size_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        Menu_PanelLayout.setVerticalGroup(
            Menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Menu_jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Menu_PanelLayout.createSequentialGroup()
                        .addComponent(Menu_jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Size_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addComponent(Basket_jButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Basket_jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("메뉴 확인", Menu_Panel);

        Storename_jLabel.setFont(new java.awt.Font("굴림", 3, 24)); // NOI18N

        Back_jButton.setText("뒤로가기");
        Back_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(Storename_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(Back_jButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Back_jButton)
                .addGap(8, 8, 8)
                .addComponent(Storename_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        String hash = Hashsearch_jTextField.getText();
        Storename_jLabel.setText(hash);
        DefaultTableModel model = (DefaultTableModel) Menu_jTable.getModel();
        DefaultTableModel model2 = (DefaultTableModel) Basket_jTable.getModel();

        Connection con = null;
        PreparedStatement st = null;
        ResultSet rs = null;

        String sql = "select * from menu_info join store_info using (store_number) where menu_info.menu_hashtag = ";

        try {
            con = DriverManager.getConnection("jdbc:mysql://115.85.182.30:3306/cse_swde_DB?zeroDateTimeBehavior=CONVERT_TO_NULL&characterEncoding=UTF-8&serverTimezone=UTC", "cse_swde", "password");
            st = con.prepareStatement(sql + "'" + hash + "'");
            JOptionPane.showMessageDialog(null, "연결성공");

            rs = st.executeQuery();
            while (rs.next()) {
                String menu = rs.getString("menu_name");
                String size = rs.getString("menu_option");
                String price = rs.getString("menu_price");

                Object data[] = {menu, size, price};
                model.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(StoreList.class.getName()).log(Level.SEVERE, null, ex);
        }

        Information info = new Information(null, null, 0);
        CareTaker caretaker = new CareTaker();
        info.RestorMemento(caretaker.pop());

        Object data2[] = {info.getData1(), info.getData2(), info.getData3()};
        model2.addRow(data2);


    }//GEN-LAST:event_formWindowOpened

    private void Back_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_jButtonActionPerformed
        // TODO add your handling code here:
        User user = new User();
        user.setVisible(true);
        dispose();

    }//GEN-LAST:event_Back_jButtonActionPerformed

    private void Menu_jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_jTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) Menu_jTable.getModel();
        int row = Menu_jTable.getSelectedRow();
        int col = Menu_jTable.getSelectedColumn();
        Menu_jTable.isCellEditable(row, col);
        if (evt.getClickCount() == 2) {

        }
        Menu_jLabel.setText(model.getValueAt(row, 0).toString());

    }//GEN-LAST:event_Menu_jTableMouseClicked

    private void Basket_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Basket_jButtonActionPerformed
        // TODO add your handling code here:
        String menu = Menu_jLabel.getText();
        String sizeBox = (String) Size_jComboBox.getSelectedItem();

        Information info = new Information(null,null, 0);
        CareTaker caretaker = new CareTaker();

        if (menu.equals("-")) {
            JOptionPane.showMessageDialog(null, "메뉴를 선택해 주세요.");
        } else {
            if (sizeBox.equals("-")) {
                JOptionPane.showMessageDialog(null, "옵션을 선택해 주세요.");
            } else {
                Menu m = new Basic();
                Price option = new OptionPrice();
                int price = option.display(); //비교가 되
                
                DefaultTableModel model = (DefaultTableModel) Basket_jTable.getModel();

                Object[] row = new Object[3];
                row[0] = menu;
                row[1] = sizeBox;
                row[2] = price;
                model.addRow(row);
                
                info.setData1(menu);
                info.setData2(sizeBox);
                info.setData3(price);
                caretaker.push(info.CreateMemento());

            }
        }
        Size_jComboBox.setSelectedItem("-");
        Menu_jLabel.setText("-");
    }//GEN-LAST:event_Basket_jButtonActionPerformed

    private void Size_jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Size_jComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Size_jComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HashtagStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HashtagStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HashtagStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HashtagStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HashtagStore().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_jButton;
    public javax.swing.JButton Basket_jButton;
    private javax.swing.JScrollPane Basket_jScrollPane;
    private javax.swing.JTabbedPane Basket_jTabbedPane;
    private javax.swing.JTable Basket_jTable;
    private javax.swing.JPanel Menu_Panel;
    public static javax.swing.JLabel Menu_jLabel;
    public static javax.swing.JLabel Menu_jLabel1;
    private javax.swing.JScrollPane Menu_jScrollPane;
    private javax.swing.JTable Menu_jTable;
    public static javax.swing.JComboBox<String> Size_jComboBox;
    private javax.swing.JLabel Storename_jLabel;
    private javax.swing.JTabbedPane jTabbedPane;
    // End of variables declaration//GEN-END:variables
}
