/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import Connect_DB.Connect_DB;
import Decorator.Basic;
import Decorator.Menu;
import GetSet.OptionValue;
import Memento.CareTaker;
import static Memento.CareTaker.mementos;
import Memento.Information;
import Strategy.OptionPrice_H;
import Strategy.Price;
import static User.User.Hashsearch_jTextField;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 김두현
 */
public class HashtagStore extends javax.swing.JFrame {

    Information info = new Information("장바구니가 없습니다", "장바구니가 없습니다", "", 0);
    CareTaker caretaker = new CareTaker();
    int sum;

    public HashtagStore() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        Menu_Panel = new javax.swing.JPanel();
        Menu_jScrollPane = new javax.swing.JScrollPane();
        Menu_jTable = new javax.swing.JTable();
        Basket_jTabbedPane = new javax.swing.JTabbedPane();
        Basket_jScrollPane = new javax.swing.JScrollPane();
        Basket_jTable = new javax.swing.JTable();
        Basket_jButton = new javax.swing.JButton();
        Menu_jLabel = new javax.swing.JLabel();
        Size_jComboBoxH = new javax.swing.JComboBox<>();
        Price_jLabel = new javax.swing.JLabel();
        Pay_jButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BasketB_jButton = new javax.swing.JButton();
        Storename_jLabel = new javax.swing.JLabel();
        Back_jButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Menu_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STORE", "MENU", "SIZE", "PRICE"
            }
        ));
        Menu_jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_jTableMouseClicked(evt);
            }
        });
        Menu_jScrollPane.setViewportView(Menu_jTable);

        Basket_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STORE", "MENU", "SIZE", "PRICE"
            }
        ));
        Basket_jScrollPane.setViewportView(Basket_jTable);

        Basket_jTabbedPane.addTab("장바구니", Basket_jScrollPane);

        Basket_jButton.setText("장바구니 담기");
        Basket_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Basket_jButtonActionPerformed(evt);
            }
        });

        Menu_jLabel.setText("-");

        Size_jComboBoxH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Small", "Medium", "Large" }));

        Price_jLabel.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N

        Pay_jButton.setText("결제하기");
        Pay_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pay_jButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("결제 가격");

        jLabel2.setText("옵션");

        jLabel3.setText("메뉴");

        BasketB_jButton.setText("장바구니 빼기");
        BasketB_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BasketB_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Menu_PanelLayout = new javax.swing.GroupLayout(Menu_Panel);
        Menu_Panel.setLayout(Menu_PanelLayout);
        Menu_PanelLayout.setHorizontalGroup(
            Menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Menu_PanelLayout.createSequentialGroup()
                        .addGroup(Menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Basket_jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                            .addComponent(Menu_jScrollPane))
                        .addGap(30, 30, 30)
                        .addGroup(Menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Basket_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Menu_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Size_jComboBoxH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BasketB_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Menu_PanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(Menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pay_jButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Menu_PanelLayout.createSequentialGroup()
                                .addGroup(Menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Price_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22))))))
        );
        Menu_PanelLayout.setVerticalGroup(
            Menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Menu_jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Menu_PanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Menu_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Size_jComboBoxH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Basket_jButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Basket_jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addGroup(Menu_PanelLayout.createSequentialGroup()
                        .addComponent(BasketB_jButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Price_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Pay_jButton))))
        );

        jTabbedPane.addTab("메뉴 확인", Menu_Panel);

        Storename_jLabel.setFont(new java.awt.Font("굴림", 3, 24)); // NOI18N

        Back_jButton.setText("뒤로가기");
        Back_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(Storename_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(Back_jButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Back_jButton)
                .addGap(8, 8, 8)
                .addComponent(Storename_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

        Price option2 = new OptionPrice_H();
        option2.myOption();

        String hash = Hashsearch_jTextField.getText();
        Storename_jLabel.setText(hash);
        DefaultTableModel model = (DefaultTableModel) Menu_jTable.getModel();
        DefaultTableModel model2 = (DefaultTableModel) Basket_jTable.getModel();

        String sql = "select * from menu_info join store_list using (store_number) where menu_info.menu_hashtag = '" + hash + "'";
        Connect_DB db = new Connect_DB();
        try {
            Connection con = db.getConnection();
            PreparedStatement preparedStatement;
            preparedStatement = con.prepareStatement(sql);
            ResultSet rs = preparedStatement.executeQuery();
            while (rs.next()) {
                String store = rs.getString("store_name");
                String menu = rs.getString("menu_name");
                String size = rs.getString("menu_option");
                String price = rs.getString("menu_price");

                Object data[] = {store, menu, size, price};
                model.addRow(data);
            }

            if (mementos.isEmpty()) {
                System.out.println(info.getData1());
            } else {
                while (!mementos.isEmpty()) {
                    info.RestorMemento(caretaker.pop());
                    Object data3[] = {info.getData0(), info.getData1(), info.getData2(), info.getData3()};
                    model2.addRow(data3);
                    sum += (int) data3[3];
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(StoreList.class.getName()).log(Level.SEVERE, null, ex);
        }

        String money = Integer.toString(sum);
        Price_jLabel.setText(money);
    }//GEN-LAST:event_formWindowOpened

    private void Back_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_jButtonActionPerformed
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel) Basket_jTable.getModel();
        int row = model.getRowCount();
        System.out.println(row);
        int col = model.getColumnCount();
        for (int i = 0; i < row; i++) {
            String store = (String) model.getValueAt(i, 0);
            String name = (String) model.getValueAt(i, 1);
            String option = (String) model.getValueAt(i, 2);
            int price = (int) model.getValueAt(i, 3);
            info.setData0(store);
            info.setData1(name);
            info.setData2(option);
            info.setData3(price);
            caretaker.push(info.CreateMemento());
        }

        User user = new User();
        user.setVisible(true);
        dispose();

    }//GEN-LAST:event_Back_jButtonActionPerformed

    private void Menu_jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_jTableMouseClicked
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel) Menu_jTable.getModel();
        int i = Menu_jTable.getSelectedRow();

        Storename_jLabel.setText(model.getValueAt(i, 0).toString());

        Menu_jLabel.setText(model.getValueAt(i, 1).toString());

        OptionValue ov = new OptionValue();
        int price = ov.getMenuPrice();
        price = Integer.parseInt(model.getValueAt(i, 3).toString());
        ov.setMenuPrice(price);

        String myOption = ov.getMyOption();
        myOption = (String) model.getValueAt(i, 2);
        ov.setMyOption(myOption);
        System.out.println(myOption);
        Price option2 = new OptionPrice_H();
        option2.myOption();


    }//GEN-LAST:event_Menu_jTableMouseClicked

    private void Basket_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Basket_jButtonActionPerformed
        // TODO add your handling code here:
        String store = Storename_jLabel.getText();
        String menu = Menu_jLabel.getText();
        String sizeBox = (String) Size_jComboBoxH.getSelectedItem();

        if (menu.equals("-")) {
            JOptionPane.showMessageDialog(null, "메뉴를 선택해 주세요.");
        } else {
            if (sizeBox.equals("-")) {
                JOptionPane.showMessageDialog(null, "옵션을 선택해 주세요.");
            } else {
                Menu m = new Basic();
                Price option = new OptionPrice_H();
                int price = option.display(); //비교가 되

                DefaultTableModel model = (DefaultTableModel) Basket_jTable.getModel();

                Object[] row = new Object[4];
                row[0] = store;
                row[1] = menu;
                row[2] = sizeBox;
                row[3] = price;
                model.addRow(row);
                sum += price;
                String money = Integer.toString(sum);
                Price_jLabel.setText(money);
            }
        }
        Size_jComboBoxH.setSelectedItem("-");
        Menu_jLabel.setText("-");
    }//GEN-LAST:event_Basket_jButtonActionPerformed

    private void Pay_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pay_jButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) Basket_jTable.getModel();
        int row = model.getRowCount();
        System.out.println(row);
        int col = model.getColumnCount();
        for (int i = 0; i < row; i++) {
            String store = (String) model.getValueAt(i, 0);
            String name = (String) model.getValueAt(i, 1);
            String option = (String) model.getValueAt(i, 2);
            int price = (int) model.getValueAt(i, 3);
            info.setData0(store);
            info.setData1(name);
            info.setData2(option);
            info.setData3(price);
            caretaker.push(info.CreateMemento());
        }

        Payment_Frame pf = new Payment_Frame();
        pf.setVisible(true);
        dispose();
    }//GEN-LAST:event_Pay_jButtonActionPerformed

    private void BasketB_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BasketB_jButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) Basket_jTable.getModel();
        int row = Basket_jTable.getSelectedRow();

        String pocket = Basket_jTable.getValueAt(row, 3).toString();
        int s = Integer.parseInt(pocket);
        sum -= s;
        String money = Integer.toString(sum);
        Price_jLabel.setText(money);
        model.removeRow(row);
    }//GEN-LAST:event_BasketB_jButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HashtagStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HashtagStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HashtagStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HashtagStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HashtagStore().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_jButton;
    private javax.swing.JButton BasketB_jButton;
    public javax.swing.JButton Basket_jButton;
    public javax.swing.JScrollPane Basket_jScrollPane;
    public javax.swing.JTabbedPane Basket_jTabbedPane;
    public javax.swing.JTable Basket_jTable;
    public javax.swing.JPanel Menu_Panel;
    public static javax.swing.JLabel Menu_jLabel;
    public javax.swing.JScrollPane Menu_jScrollPane;
    public javax.swing.JTable Menu_jTable;
    private javax.swing.JButton Pay_jButton;
    public javax.swing.JLabel Price_jLabel;
    public static javax.swing.JComboBox<String> Size_jComboBoxH;
    private javax.swing.JLabel Storename_jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTabbedPane jTabbedPane;
    // End of variables declaration//GEN-END:variables
}
