/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import Connect_DB.Connect_DB;
import GetSet.StoreNum;
import GetSet.OptionValue;
import Decorator.Basic;
import Decorator.Menu;
import Memento.CareTaker;
import static Memento.CareTaker.mementos;
import Memento.Information;
import Strategy.Price;
import Strategy.OptionPrice;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 김두현
 */
public class Store extends javax.swing.JFrame {

    Information info = new Information(null, null, null, 0);
    CareTaker caretaker = new CareTaker();
    int sum;

    public Store() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        Menu_Panel = new javax.swing.JPanel();
        Menu_jScrollPane = new javax.swing.JScrollPane();
        Menu_jTable = new javax.swing.JTable();
        Basket_jButton = new javax.swing.JButton();
        Menu_jLabel = new javax.swing.JLabel();
        Basket_jTabbedPane = new javax.swing.JTabbedPane();
        Basket_jScrollPane = new javax.swing.JScrollPane();
        Basket_jTable = new javax.swing.JTable();
        Size_jComboBox = new javax.swing.JComboBox<>();
        Price_jLabel = new javax.swing.JLabel();
        Pay_jButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BasketB_jButton = new javax.swing.JButton();
        Storeinfo_jPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        time_Label = new javax.swing.JLabel();
        day_Label = new javax.swing.JLabel();
        add_Label = new javax.swing.JLabel();
        phone_Label = new javax.swing.JLabel();
        tip_Label = new javax.swing.JLabel();
        detail_Label = new javax.swing.JLabel();
        Review_jPanel = new javax.swing.JPanel();
        Review_jTextField = new javax.swing.JTextField();
        Review_jScrollPane = new javax.swing.JScrollPane();
        Review_jTable = new javax.swing.JTable();
        Review_jButton = new javax.swing.JButton();
        Review_jSlider = new javax.swing.JSlider();
        Review_jLabel = new javax.swing.JLabel();
        Storename_jLabel = new javax.swing.JLabel();
        Back_jButton = new javax.swing.JButton();
        Totalreview_jLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Menu_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MENU", "SIZE", "PRICE"
            }
        ));
        Menu_jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_jTableMouseClicked(evt);
            }
        });
        Menu_jScrollPane.setViewportView(Menu_jTable);

        Basket_jButton.setText("장바구니 담기");
        Basket_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Basket_jButtonActionPerformed(evt);
            }
        });

        Menu_jLabel.setText("-");

        Basket_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STORE", "MENU", "SIZE", "PRICE"
            }
        ));
        Basket_jScrollPane.setViewportView(Basket_jTable);

        Basket_jTabbedPane.addTab("장바구니", Basket_jScrollPane);

        Size_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Small", "Medium", "Large" }));

        Price_jLabel.setFont(new java.awt.Font("굴림", 1, 14)); // NOI18N
        Price_jLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Pay_jButton.setText("결제하기");
        Pay_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pay_jButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("메뉴");

        jLabel2.setText("옵션");

        jLabel3.setText("결제 가격");

        BasketB_jButton.setText("장바구니 빼기");
        BasketB_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BasketB_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Menu_PanelLayout = new javax.swing.GroupLayout(Menu_Panel);
        Menu_Panel.setLayout(Menu_PanelLayout);
        Menu_PanelLayout.setHorizontalGroup(
            Menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Basket_jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                    .addComponent(Menu_jScrollPane))
                .addGap(18, 18, 18)
                .addGroup(Menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(Menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Menu_PanelLayout.createSequentialGroup()
                                .addGroup(Menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Basket_jButton)
                                    .addComponent(Size_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                            .addComponent(Pay_jButton, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(Menu_PanelLayout.createSequentialGroup()
                            .addComponent(Price_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(20, 20, 20)))
                    .addGroup(Menu_PanelLayout.createSequentialGroup()
                        .addGroup(Menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Menu_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(BasketB_jButton, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        Menu_PanelLayout.setVerticalGroup(
            Menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Menu_jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Menu_PanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Menu_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(5, 5, 5)
                        .addComponent(Size_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Basket_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Menu_PanelLayout.createSequentialGroup()
                        .addComponent(BasketB_jButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Price_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Pay_jButton)
                        .addContainerGap())
                    .addComponent(Basket_jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)))
        );

        jTabbedPane.addTab("메뉴 확인", Menu_Panel);

        jLabel4.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel4.setText("가게 소개");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel5.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel5.setText("운영 정보");

        jLabel6.setFont(new java.awt.Font("굴림", 1, 13)); // NOI18N
        jLabel6.setText("운영 시간");

        jLabel7.setFont(new java.awt.Font("굴림", 1, 13)); // NOI18N
        jLabel7.setText("휴  무  일");

        jLabel8.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel8.setText("가게 정보");

        jLabel9.setFont(new java.awt.Font("굴림", 1, 13)); // NOI18N
        jLabel9.setText("가게 주소");

        jLabel10.setFont(new java.awt.Font("굴림", 1, 13)); // NOI18N
        jLabel10.setText("가게 번호");

        jLabel11.setFont(new java.awt.Font("굴림", 1, 13)); // NOI18N
        jLabel11.setText("배  달  팁");

        javax.swing.GroupLayout Storeinfo_jPanelLayout = new javax.swing.GroupLayout(Storeinfo_jPanel);
        Storeinfo_jPanel.setLayout(Storeinfo_jPanelLayout);
        Storeinfo_jPanelLayout.setHorizontalGroup(
            Storeinfo_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Storeinfo_jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Storeinfo_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addGroup(Storeinfo_jPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(Storeinfo_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Storeinfo_jPanelLayout.createSequentialGroup()
                                .addGroup(Storeinfo_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(Storeinfo_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(day_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                                    .addComponent(time_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(Storeinfo_jPanelLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(phone_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE))
                            .addGroup(Storeinfo_jPanelLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(tip_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE))
                            .addGroup(Storeinfo_jPanelLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addGroup(Storeinfo_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(detail_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                                    .addComponent(add_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        Storeinfo_jPanelLayout.setVerticalGroup(
            Storeinfo_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Storeinfo_jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Storeinfo_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(time_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Storeinfo_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(day_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Storeinfo_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(add_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detail_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Storeinfo_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(phone_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(Storeinfo_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tip_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("가맹점 정보", Storeinfo_jPanel);

        Review_jTextField.setText("리뷰 작성란");
        Review_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Review_jTextFieldActionPerformed(evt);
            }
        });

        Review_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "리뷰", "평점", "작성일"
            }
        ));
        Review_jScrollPane.setViewportView(Review_jTable);

        Review_jButton.setText("작성");
        Review_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Review_jButtonActionPerformed(evt);
            }
        });

        Review_jSlider.setMaximum(5);
        Review_jSlider.setMinimum(1);
        Review_jSlider.setToolTipText("");
        Review_jSlider.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));

        Review_jLabel.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N

        javax.swing.GroupLayout Review_jPanelLayout = new javax.swing.GroupLayout(Review_jPanel);
        Review_jPanel.setLayout(Review_jPanelLayout);
        Review_jPanelLayout.setHorizontalGroup(
            Review_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Review_jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Review_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Review_jTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                    .addComponent(Review_jScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Review_jPanelLayout.createSequentialGroup()
                        .addComponent(Review_jSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Review_jButton)))
                .addContainerGap())
            .addGroup(Review_jPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(Review_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Review_jPanelLayout.setVerticalGroup(
            Review_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Review_jPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Review_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Review_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Review_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Review_jPanelLayout.createSequentialGroup()
                        .addComponent(Review_jSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Review_jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Review_jPanelLayout.createSequentialGroup()
                        .addComponent(Review_jButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane.addTab("리뷰 작성", Review_jPanel);

        Storename_jLabel.setFont(new java.awt.Font("굴림", 3, 24)); // NOI18N

        Back_jButton.setText("뒤로가기");
        Back_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_jButtonActionPerformed(evt);
            }
        });

        Totalreview_jLabel.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(Storename_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Totalreview_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addComponent(Back_jButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Back_jButton)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Totalreview_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Storename_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_jTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) Menu_jTable.getModel();
        int i = Menu_jTable.getSelectedRow();

        Menu_jLabel.setText(model.getValueAt(i, 0).toString());

        OptionValue ov = new OptionValue();
        int price = ov.getMenuPrice();
        price = Integer.parseInt(model.getValueAt(i, 2).toString());
        ov.setMenuPrice(price);

        String myOption = ov.getMyOption();
        myOption = (String) model.getValueAt(i, 1);
        ov.setMyOption(myOption);
        System.out.println(myOption);
        Price option2 = new OptionPrice();
        option2.myOption();

    }//GEN-LAST:event_Menu_jTableMouseClicked

    private void Basket_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Basket_jButtonActionPerformed
        // TODO add your handling code here:
        String store = Storename_jLabel.getText();
        String menu = Menu_jLabel.getText();
        String sizeBox = (String) Size_jComboBox.getSelectedItem();

        if (menu.equals("-")) {
            JOptionPane.showMessageDialog(null, "메뉴를 선택해 주세요.");
        } else {
            if (sizeBox.equals("-")) {
                JOptionPane.showMessageDialog(null, "옵션을 선택해 주세요.");
            } else {
                Menu m = new Basic();
                Price option2 = new OptionPrice();
                int price = option2.display();

                DefaultTableModel model = (DefaultTableModel) Basket_jTable.getModel();

                Object[] row = new Object[4];
                row[0] = store;
                row[1] = menu;
                row[2] = sizeBox;
                row[3] = price;
                model.addRow(row);

                sum += price;
                String money = Integer.toString(sum);
                Price_jLabel.setText(money);
            }
        }

        Size_jComboBox.setSelectedItem("-");
        Menu_jLabel.setText("-");
    }//GEN-LAST:event_Basket_jButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Price option2 = new OptionPrice();
        option2.myOption();

        StoreNum storelist = new StoreNum();
        String sl = storelist.getStoreList();

        Storename_jLabel.setText(sl);
        String s = storelist.getStore();
        DefaultTableModel model1 = (DefaultTableModel) Menu_jTable.getModel();
        DefaultTableModel model2 = (DefaultTableModel) Review_jTable.getModel();
        DefaultTableModel model3 = (DefaultTableModel) Basket_jTable.getModel();

        String menuSql = "select * from menu_info where menu_info.store_number = '" + s + "'";
        String myRating = "select avg(rating) from reviews where reviews.store_number = '" + s + "'";
        String reviewSql = "select * from reviews where store_number = '" + s + "'";
        String storeSql = "select * from store_info where store_number = '" + s + "'";
        Connect_DB db = new Connect_DB();
        try {
            Connection con = db.getConnection();
            PreparedStatement preparedStatement = null;
            preparedStatement = con.prepareStatement(myRating);
            ResultSet rs = preparedStatement.executeQuery();
            while (rs.next()) {
                String myRating2 = rs.getString("avg(rating)");
                Totalreview_jLabel.setText(myRating2);
            }
            //메뉴
            preparedStatement = con.prepareStatement(menuSql);
            rs = preparedStatement.executeQuery();
            while (rs.next()) {
                String menu = rs.getString("menu_name");
                String option = rs.getString("menu_option");
                String price = rs.getString("menu_price");
                Object data[] = {menu, option, price};
                model1.addRow(data);
            }

            //리뷰
            preparedStatement = con.prepareStatement(reviewSql);
            ResultSet rss = preparedStatement.executeQuery();

            while (rss.next()) {
                String id = rss.getString("id");
                String review = rss.getString("review");
                String storeRating = rss.getString("rating");
                String nowTime = rss.getString("time");
                Object data2[] = {id, review, storeRating, nowTime};
                model2.addRow(data2);
            }

            //가게 정보
            preparedStatement = con.prepareStatement(storeSql);
            rs = preparedStatement.executeQuery();
            if (rs.next()) {
                String intro = rs.getString("store_introduction");
                String time = rs.getString("store_operatingtime");
                String day = rs.getString("store_closeddays");
                String phone = rs.getString("store_phone");
                String add[] = rs.getString("store_address").split("/");
                String tip = rs.getString("store_deliverycost");

                jTextArea1.setText(intro);
                time_Label.setText(time);
                day_Label.setText(day);
                phone_Label.setText(phone);
                add_Label.setText(add[0]);
                detail_Label.setText(add[1]);
                tip_Label.setText(tip);
            }

            //장바구니
            if (mementos.isEmpty()) {
                JOptionPane.showMessageDialog(null, "장바구니 내용이 비어있습니다");
            } else {
                while (!mementos.isEmpty()) {
                    info.RestorMemento(caretaker.pop());
                    Object data3[] = {info.getData0(), info.getData1(), info.getData2(), info.getData3()};
                    model3.addRow(data3);
                    sum += (int) data3[3];
                }
            }
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(StoreList.class.getName()).log(Level.SEVERE, null, ex);
        }
        String money = Integer.toString(sum);
        Price_jLabel.setText(money);
    }//GEN-LAST:event_formWindowOpened

    private void Pay_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pay_jButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) Basket_jTable.getModel();
        int row = model.getRowCount();
        System.out.println(row);
        int col = model.getColumnCount();
        for (int i = 0; i < row; i++) {
            String store = (String) model.getValueAt(i, 0);
            String name = (String) model.getValueAt(i, 1);
            String option = (String) model.getValueAt(i, 2);
            int price = (int) model.getValueAt(i, 3);
            info.setData0(store);
            info.setData1(name);
            info.setData2(option);
            info.setData3(price);
            caretaker.push(info.CreateMemento());
        }

        Payment_Frame pf = new Payment_Frame();
        pf.setVisible(true);
        dispose();
    }//GEN-LAST:event_Pay_jButtonActionPerformed

    private void Back_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_jButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) Basket_jTable.getModel();
        int row = model.getRowCount();
        System.out.println(row);
        int col = model.getColumnCount();
        for (int i = 0; i < row; i++) {
            String store = (String) model.getValueAt(i, 0);
            String name = (String) model.getValueAt(i, 1);
            String option = (String) model.getValueAt(i, 2);
            int price = (int) model.getValueAt(i, 3);
            info.setData0(store);
            info.setData1(name);
            info.setData2(option);
            info.setData3(price);
            caretaker.push(info.CreateMemento());
        }

        User user = new User();
        user.setVisible(true);
        dispose();

    }//GEN-LAST:event_Back_jButtonActionPerformed

    private void Review_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Review_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Review_jTextFieldActionPerformed

    private void Review_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Review_jButtonActionPerformed
        // TODO add your handling code here:

        StoreNum storelist = new StoreNum();
        String s = storelist.getStore();

        int rating = Review_jSlider.getValue();
        String ratingCheck = rating + "점";
        Review_jLabel.setText(ratingCheck);

        SimpleDateFormat date = new SimpleDateFormat("yyyy년 MM월dd일 HH시mm분ss초");
        Date time = new Date();
        String now = date.format(time);

        DefaultTableModel model = (DefaultTableModel) Review_jTable.getModel();
        String reviewText = "insert into reviews (id, store_number, review, rating, time) values (?, ?, ?, ?, ?)";
        String reviewInput = Review_jTextField.getText();
        Connect_DB db = new Connect_DB();
        try {
            Connection con = db.getConnection();
            PreparedStatement preparedStatement = null;
            preparedStatement = con.prepareStatement(reviewText);
            preparedStatement.setString(1, Login.Login_Frame.Login_Session);
            preparedStatement.setString(2, s);
            preparedStatement.setString(3, reviewInput);
            preparedStatement.setInt(4, rating);
            preparedStatement.setString(5, now);
            int num = preparedStatement.executeUpdate();

            Object review[] = new Object[4];
            review[0] = Login.Login_Frame.Login_Session;
            review[1] = reviewInput;
            review[2] = rating;
            review[3] = now;

            model.addRow(review);

            String myRating = "select round(avg(rating),2) from reviews where store_number = '" + s + "'";
            preparedStatement = con.prepareStatement(myRating);
            ResultSet rs = preparedStatement.executeQuery();
            while (rs.next()) {
                String myRating2 = rs.getString("round(avg(rating),2)");
                Totalreview_jLabel.setText(myRating2);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Store.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_Review_jButtonActionPerformed

    private void BasketB_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BasketB_jButtonActionPerformed
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel) Basket_jTable.getModel();
        int row = Basket_jTable.getSelectedRow();

        String pocket = Basket_jTable.getValueAt(row, 3).toString();
        int s = Integer.parseInt(pocket);
        sum -= s;
        String money = Integer.toString(sum);
        Price_jLabel.setText(money);

        model.removeRow(row);
    }//GEN-LAST:event_BasketB_jButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Store().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_jButton;
    private javax.swing.JButton BasketB_jButton;
    public javax.swing.JButton Basket_jButton;
    public javax.swing.JScrollPane Basket_jScrollPane;
    public javax.swing.JTabbedPane Basket_jTabbedPane;
    public javax.swing.JTable Basket_jTable;
    public javax.swing.JPanel Menu_Panel;
    public static javax.swing.JLabel Menu_jLabel;
    public javax.swing.JScrollPane Menu_jScrollPane;
    public javax.swing.JTable Menu_jTable;
    private javax.swing.JButton Pay_jButton;
    public javax.swing.JLabel Price_jLabel;
    private javax.swing.JButton Review_jButton;
    private javax.swing.JLabel Review_jLabel;
    private javax.swing.JPanel Review_jPanel;
    private javax.swing.JScrollPane Review_jScrollPane;
    private javax.swing.JSlider Review_jSlider;
    private javax.swing.JTable Review_jTable;
    public javax.swing.JTextField Review_jTextField;
    public static javax.swing.JComboBox<String> Size_jComboBox;
    private javax.swing.JPanel Storeinfo_jPanel;
    private javax.swing.JLabel Storename_jLabel;
    private javax.swing.JLabel Totalreview_jLabel;
    private javax.swing.JLabel add_Label;
    private javax.swing.JLabel day_Label;
    private javax.swing.JLabel detail_Label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel phone_Label;
    private javax.swing.JLabel time_Label;
    private javax.swing.JLabel tip_Label;
    // End of variables declaration//GEN-END:variables
}
