/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import static User.StoreNum.storeList;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 김두현
 */
public class User extends javax.swing.JFrame {

    /**
     * Creates new form User
     */
    public User() {
        initComponents();
    }
    Connection con;
    Statement st;
    ResultSet rs;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        카페_jButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        치킨피자_jButton = new javax.swing.JButton();
        야식_jButton = new javax.swing.JButton();
        분식_jButton = new javax.swing.JButton();
        족발보쌈_jButton = new javax.swing.JButton();
        패스트푸드_jButton = new javax.swing.JButton();
        중국집_jButton = new javax.swing.JButton();
        양식_jButton = new javax.swing.JButton();
        일식회_jButton = new javax.swing.JButton();
        메뉴검색_jButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        카페_jButton.setText("카페");
        카페_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                카페_jButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("팀프로젝트");

        치킨피자_jButton.setText("치킨/피자");
        치킨피자_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                치킨피자_jButtonActionPerformed(evt);
            }
        });

        야식_jButton.setText("야식");
        야식_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                야식_jButtonActionPerformed(evt);
            }
        });

        분식_jButton.setText("분식");
        분식_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                분식_jButtonActionPerformed(evt);
            }
        });

        족발보쌈_jButton.setText("족발/보쌈");

        패스트푸드_jButton.setText("패스트푸드");
        패스트푸드_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                패스트푸드_jButtonActionPerformed(evt);
            }
        });

        중국집_jButton.setText("중국집");
        중국집_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                중국집_jButtonActionPerformed(evt);
            }
        });

        양식_jButton.setText("양식");
        양식_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                양식_jButtonActionPerformed(evt);
            }
        });

        일식회_jButton.setText("일식/회");
        일식회_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                일식회_jButtonActionPerformed(evt);
            }
        });

        메뉴검색_jButton.setText("메뉴검색하기");
        메뉴검색_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                메뉴검색_jButtonActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(메뉴검색_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(카페_jButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(치킨피자_jButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(야식_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(패스트푸드_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(분식_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(족발보쌈_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(중국집_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(양식_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(일식회_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextField1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(중국집_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(카페_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(분식_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(양식_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(족발보쌈_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(치킨피자_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(야식_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(일식회_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(패스트푸드_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(메뉴검색_jButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void 카페_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_카페_jButtonActionPerformed
        StoreCategory sc = new StoreCategory();
        String storeCategory = sc.getStoreCategory();
        storeCategory = "카페";
        sc.setHashSearch(storeCategory);

        StoreList cafe = new StoreList();
        cafe.setVisible(true);
        dispose();

    }//GEN-LAST:event_카페_jButtonActionPerformed

    private void 치킨피자_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_치킨피자_jButtonActionPerformed
        // TODO add your handling code here:
        StoreCategory sc = new StoreCategory();
        String storeCategory = sc.getStoreCategory();
        storeCategory = "치킨/피자";
        sc.setHashSearch(storeCategory);

        StoreList cafe = new StoreList();
        cafe.setVisible(true);
        dispose();

    }//GEN-LAST:event_치킨피자_jButtonActionPerformed

    private void 야식_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_야식_jButtonActionPerformed
        // TODO add your handling code here:
        StoreCategory sc = new StoreCategory();
        String storeCategory = sc.getStoreCategory();
        storeCategory = "야식";
        sc.setHashSearch(storeCategory);

        StoreList cafe = new StoreList();
        cafe.setVisible(true);
        dispose();

    }//GEN-LAST:event_야식_jButtonActionPerformed

    private void 패스트푸드_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_패스트푸드_jButtonActionPerformed
        // TODO add your handling code here:
        StoreCategory sc = new StoreCategory();
        String storeCategory = sc.getStoreCategory();
        storeCategory = "패스트푸드";
        sc.setHashSearch(storeCategory);

        StoreList cafe = new StoreList();
        cafe.setVisible(true);
        dispose();

    }//GEN-LAST:event_패스트푸드_jButtonActionPerformed

    private void 일식회_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_일식회_jButtonActionPerformed
        // TODO add your handling code here:
        StoreCategory sc = new StoreCategory();
        String storeCategory = sc.getStoreCategory();
        storeCategory = "일식/회";
        sc.setHashSearch(storeCategory);

        StoreList cafe = new StoreList();
        cafe.setVisible(true);
        dispose();

    }//GEN-LAST:event_일식회_jButtonActionPerformed

    private void 분식_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_분식_jButtonActionPerformed
        // TODO add your handling code here:
        StoreCategory sc = new StoreCategory();
        String storeCategory = sc.getStoreCategory();
        storeCategory = "분식";
        sc.setHashSearch(storeCategory);

        StoreList cafe = new StoreList();
        cafe.setVisible(true);
        dispose();

    }//GEN-LAST:event_분식_jButtonActionPerformed

    private void 중국집_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_중국집_jButtonActionPerformed
        // TODO add your handling code here:
        StoreCategory sc = new StoreCategory();
        String storeCategory = sc.getStoreCategory();
        storeCategory = "중국집";
        sc.setHashSearch(storeCategory);

        StoreList cafe = new StoreList();
        cafe.setVisible(true);
        dispose();


    }//GEN-LAST:event_중국집_jButtonActionPerformed

    private void 양식_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_양식_jButtonActionPerformed
        // TODO add your handling code here:
        StoreCategory sc = new StoreCategory();
        String storeCategory = sc.getStoreCategory();
        storeCategory = "양식";
        sc.setHashSearch(storeCategory);

        StoreList cafe = new StoreList();
        cafe.setVisible(true);
        dispose();

    }//GEN-LAST:event_양식_jButtonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void 메뉴검색_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_메뉴검색_jButtonActionPerformed
        // TODO add your handling code here:
        HashSearch hashsearch = new HashSearch();
        String k = hashsearch.getHashSearch();

        k = jTextField1.getText();
        hashsearch.setHashSearch(k);

        HashtagStore hs = new HashtagStore();
        hs.setVisible(true);
        dispose();

    }//GEN-LAST:event_메뉴검색_jButtonActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        HashSearch hashsearch = new HashSearch();
        String k = hashsearch.getHashSearch();

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            k = jTextField1.getText();
            hashsearch.setHashSearch(k);

            HashtagStore hs = new HashtagStore();
            hs.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton 메뉴검색_jButton;
    private javax.swing.JButton 분식_jButton;
    private javax.swing.JButton 야식_jButton;
    private javax.swing.JButton 양식_jButton;
    private javax.swing.JButton 일식회_jButton;
    private javax.swing.JButton 족발보쌈_jButton;
    private javax.swing.JButton 중국집_jButton;
    private javax.swing.JButton 치킨피자_jButton;
    private javax.swing.JButton 카페_jButton;
    private javax.swing.JButton 패스트푸드_jButton;
    // End of variables declaration//GEN-END:variables
}
