/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Address_API;

import javax.swing.JList;


/**
 *
 * @author rlarl
 */
public class Search_Address_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Search_Address_Frame
     */
    static public String[] Select_Adr;
    
    public Search_Address_Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        Adr_List = new javax.swing.JList<>();
        Adr_RButton = new javax.swing.JRadioButton();
        Radr_RButton = new javax.swing.JRadioButton();
        Adr_Field = new javax.swing.JTextField();
        Search_Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Adr_List.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Adr_List.setToolTipText("");
        Adr_List.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Adr_List.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        Adr_List.setDoubleBuffered(true);
        Adr_List.setMaximumSize(new java.awt.Dimension(532, 16));
        Adr_List.setMinimumSize(new java.awt.Dimension(532, 16));
        Adr_List.setName(""); // NOI18N
        Adr_List.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Adr_ListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Adr_List);

        buttonGroup1.add(Adr_RButton);
        Adr_RButton.setFont(new java.awt.Font("굴림", 0, 10)); // NOI18N
        Adr_RButton.setSelected(true);
        Adr_RButton.setText("지번");
        Adr_RButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        buttonGroup1.add(Radr_RButton);
        Radr_RButton.setFont(new java.awt.Font("굴림", 0, 10)); // NOI18N
        Radr_RButton.setText("도로명");
        Radr_RButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        Search_Button.setText("검색");
        Search_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_ButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("굴림", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("* 지번명(도로명)과 건물번호를 입력하세요.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Radr_RButton)
                            .addComponent(Adr_RButton))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(Adr_Field))
                        .addGap(18, 18, 18)
                        .addComponent(Search_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Adr_RButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Radr_RButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Adr_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Search_Button))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Search_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_ButtonActionPerformed
        Address_API api = new Address_API();
        api.get_Data();
        Adr_List.setModel(api.set_Data());
    }//GEN-LAST:event_Search_ButtonActionPerformed

    private void Adr_ListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Adr_ListMouseClicked
        JList<String> theList = (JList) evt.getSource();
        if (evt.getClickCount() == 2) {
          int index = theList.locationToIndex(evt.getPoint());
          if (index >= 0) {
            Object o = theList.getModel().getElementAt(index);
            Select_Adr = o.toString().split("/");
            System.out.println(Select_Adr[0]);
            System.out.println(Select_Adr[1]);
            dispose();
          }
        }
    }//GEN-LAST:event_Adr_ListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search_Address_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search_Address_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search_Address_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search_Address_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search_Address_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField Adr_Field;
    public javax.swing.JList<String> Adr_List;
    public static javax.swing.JRadioButton Adr_RButton;
    public static javax.swing.JRadioButton Radr_RButton;
    private javax.swing.JButton Search_Button;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
