/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NewUser;

import Address_API.dial;
import Connect_DB.Connect_DB;
import Login.Login_Frame;
import java.awt.Color;
import java.awt.Cursor;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author 김기태
 */
public class User_Frame extends javax.swing.JFrame {

    boolean flag;
    String[] data;
    public User_Frame() {
        initComponents();
        Warning_Label.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR)); // 경고 아이콘에 기능 추가
        Group.add(M_RButton); //라디오 버튼 그룹으로 묶음
        Group.add(FM_RButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Group = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ID_Field = new javax.swing.JTextField();
        Name_Field = new javax.swing.JTextField();
        Age_Field = new javax.swing.JTextField();
        Address_Field = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        M_RButton = new javax.swing.JRadioButton();
        FM_RButton = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        PW_Field = new javax.swing.JPasswordField();
        RePW_Field = new javax.swing.JPasswordField();
        Overlap_Test = new javax.swing.JButton();
        End_Button = new javax.swing.JButton();
        Overlap_Label = new javax.swing.JLabel();
        PW_Test_Label = new javax.swing.JLabel();
        RePW_Test_Label = new javax.swing.JLabel();
        Warning_Label = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        RRN_Field = new javax.swing.JFormattedTextField();
        Address_Button = new javax.swing.JButton();
        Set_Address = new javax.swing.JTextField();
        Detail_Address = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        jLabel1.setText("개인 회원 회원가입");

        jLabel2.setText("I D");

        jLabel3.setText("PW");

        jLabel4.setText("이 름");

        jLabel5.setText("나 이");

        jLabel6.setText("주 소");

        Age_Field.setEditable(false);
        Age_Field.setAutoscrolls(false);
        Age_Field.setFocusable(false);

        Address_Field.setEditable(false);
        Address_Field.setFocusable(false);

        jLabel7.setText("성 별");

        M_RButton.setText("남");

        FM_RButton.setText("여");

        jLabel8.setText("재확인");

        PW_Field.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                PW_FieldCaretUpdate(evt);
            }
        });

        RePW_Field.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                RePW_FieldCaretUpdate(evt);
            }
        });

        Overlap_Test.setText("중복확인");
        Overlap_Test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Overlap_TestActionPerformed(evt);
            }
        });

        End_Button.setText("확인");
        End_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                End_ButtonActionPerformed(evt);
            }
        });

        PW_Test_Label.setForeground(new java.awt.Color(255, 51, 51));

        RePW_Test_Label.setForeground(new java.awt.Color(255, 51, 51));

        Warning_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NewUser/경고.png"))); // NOI18N
        Warning_Label.setToolTipText("패스워드는 영문자, 숫자를 사용한 7자 이상이어야 합니다.");

        jLabel9.setText("주민등록번호");

        try {
            RRN_Field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######-#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        RRN_Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                RRN_FieldFocusLost(evt);
            }
        });

        Address_Button.setText("주소검색");
        Address_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Address_ButtonActionPerformed(evt);
            }
        });

        Set_Address.setEditable(false);
        Set_Address.setFocusable(false);

        jLabel10.setText("상세 주소");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel2))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(Warning_Label)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel3)))
                                        .addComponent(jLabel8))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ID_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(RRN_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(Overlap_Test))
                                    .addComponent(Overlap_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(M_RButton)
                                                .addGap(26, 26, 26)
                                                .addComponent(FM_RButton))
                                            .addComponent(RePW_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RePW_Test_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(PW_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(PW_Test_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Name_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Age_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Address_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Address_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Set_Address)
                            .addComponent(Detail_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(End_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Name_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(Age_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(RRN_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ID_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Overlap_Test))
                .addGap(3, 3, 3)
                .addComponent(Overlap_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PW_Test_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Warning_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PW_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RePW_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addComponent(RePW_Test_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(M_RButton)
                    .addComponent(FM_RButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Address_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Address_Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Set_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Detail_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(End_Button)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Overlap_TestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Overlap_TestActionPerformed
        String ID = ID_Field.getText(); //ID 값 변수
        try{
            Connect_DB db = new Connect_DB();
            db.Use_DB();
            ResultSet rs = db.Command_ExecuteQuery("select ID from Actor where ID='"+ID+"'"); //ID가 입력받은 ID와 같은 데이터 검사
            if(rs.next()){ //같은 ID가 있으면
                Overlap_Label.setText("이미 존재하는 아이디입니다.");
                Overlap_Label.setForeground(Color.red);
                flag = false; //확인 값
            }
            else{
                ID_Field.setEnabled(false);
                Overlap_Label.setText("사용 가능한 아이디입니다.");
                Overlap_Label.setForeground(Color.blue);
                flag = true; //확인 값
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_Overlap_TestActionPerformed

    private void PW_FieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_PW_FieldCaretUpdate
        if(PW_Field.getText().equals("")){ //텍스트 필드가 비어있는 경우
            PW_Test_Label.setText("비어있음.");
            PW_Test_Label.setForeground(Color.red);
        }
        else if(PW_Field.getText().length()<7){ //텍스트 필드의 값이 7자리 이하
            PW_Test_Label.setText("너무 짧습니다.");
            PW_Test_Label.setForeground(Color.red);
        }
        else{//텍스트 필드 길이가 조건에 만족 시
            boolean Number = false; //영문자 판별 부호
            boolean Alpha = false; //숫자 판별 부호
            for(int i=0; i<PW_Field.getText().length();i++){
            int index = PW_Field.getText().charAt(i);
            
            if(index>=65 && index<=122){ //영어 검출
                Alpha = true;  
            }
            else if(index<=57 && index >= 48){//숫자 검출
                Number = true;
            }
           }
            if(Number==false){
                PW_Test_Label.setText("숫자를 포함해 주세요.");
            }
            else if(Alpha==false){
                PW_Test_Label.setText("영문자를 포함해 주세요");
            }
            else{//모든 조건 만족
                PW_Test_Label.setText("O");
                PW_Test_Label.setForeground(Color.blue);
            }
        }
    }//GEN-LAST:event_PW_FieldCaretUpdate

    private void RePW_FieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_RePW_FieldCaretUpdate
        if(RePW_Field.getText().equals("")){
            RePW_Test_Label.setText("비어있음.");
            RePW_Test_Label.setForeground(Color.red);
        }
        else if(!RePW_Field.getText().equals(PW_Field.getText())){//이전에 입력한 패스워드와 불일치 시
            RePW_Test_Label.setText("일치하지 않습니다.");
            RePW_Test_Label.setForeground(Color.red);
        } else if(RePW_Field.getText().equals(PW_Field.getText())){
            RePW_Test_Label.setText("O");
            RePW_Test_Label.setForeground(Color.blue);
        }
    }//GEN-LAST:event_RePW_FieldCaretUpdate

    private void End_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_End_ButtonActionPerformed
        if((flag)
            &&(PW_Test_Label.getText().equals("O"))
            &&(RePW_Test_Label.getText().equals("O"))
            &&(!Name_Field.getText().equals(""))
            &&(!RRN_Field.getText().equals(""))
            &&(!Address_Field.getText().equals(""))){
                String ID = ID_Field.getText();
                String PW = PW_Field.getText();
                String Name = Name_Field.getText();
                String RRN = RRN_Field.getText();
                int Age = Integer.parseInt(Age_Field.getText());
                String Gender="";
                if(M_RButton.isSelected()){
                    Gender = M_RButton.getText();
                }
                else if(FM_RButton.isSelected()){
                    Gender = FM_RButton.getText();
                }
                String Address = (Set_Address.getText()+"/"+Detail_Address.getText());
                System.out.println(Address);
                
                int bool = JOptionPane.showConfirmDialog(null, "입력하신 정보로 가입하시겠습니까?", "회원가입", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
                
                if(bool==0){
                    Connect_DB db = new Connect_DB();
                    db.Use_DB();
                    db.Command_ExecuteUpdate("insert into Actor values('"+ID+"', '"+PW+"', '"+RRN+"', '"+Name+"', '"+Age+"', '"+Gender+"', '"+Address+"', 'user');");
                    JOptionPane.showMessageDialog(null, "회원가입 완료");
                    Login_Frame frame = new Login_Frame();
                    frame.setVisible(true);
                    dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "회원가입 취소");
                }
                
        }
        else{
            JOptionPane.showMessageDialog(null, "다시 한번 확인하세요.","회원가입 실패", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_End_ButtonActionPerformed

    private void RRN_FieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RRN_FieldFocusLost
        String years = RRN_Field.getText();
        years = years.substring(0, 2);
        if(Integer.parseInt(years)>50){
            years="19"+years;
        }
        else{
             years="20"+years;
        }
        int year = Integer.parseInt(years);
        Age_Field.setText(Integer.toString(2021-year+1));
    }//GEN-LAST:event_RRN_FieldFocusLost

    private void Address_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Address_ButtonActionPerformed
        dial s = new dial(this, true);
        s.setVisible(true);
        if(s.isFocusOwner()){
            System.out.println("on");
        }else{
            System.out.println("off");
            data=dial.Select_Adr;
            Address_Field.setText(data[0]);
            Set_Address.setText(data[1]);
        }
    }//GEN-LAST:event_Address_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Address_Button;
    private javax.swing.JTextField Address_Field;
    private javax.swing.JTextField Age_Field;
    private javax.swing.JTextField Detail_Address;
    private javax.swing.JButton End_Button;
    private javax.swing.JRadioButton FM_RButton;
    private javax.swing.ButtonGroup Group;
    private javax.swing.JTextField ID_Field;
    private javax.swing.JRadioButton M_RButton;
    private javax.swing.JTextField Name_Field;
    private javax.swing.JLabel Overlap_Label;
    private javax.swing.JButton Overlap_Test;
    private javax.swing.JPasswordField PW_Field;
    private javax.swing.JLabel PW_Test_Label;
    private javax.swing.JFormattedTextField RRN_Field;
    private javax.swing.JPasswordField RePW_Field;
    private javax.swing.JLabel RePW_Test_Label;
    private javax.swing.JTextField Set_Address;
    private javax.swing.JLabel Warning_Label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
